--- #YAML:1.0
name:                Tie-Slurp-Cached
version:             0.03
abstract:            slurps with locks a la perltie
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
